/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing AutosnapResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AutosnapResourceTests
    {
        // TODO uncomment below to declare an instance variable for AutosnapResource
        //private AutosnapResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AutosnapResource
            //instance = new AutosnapResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutosnapResource
        /// </summary>
        [Test]
        public void AutosnapResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AutosnapResource
            //Assert.IsInstanceOfType<AutosnapResource> (instance, "variable 'instance' is a AutosnapResource");
        }


        /// <summary>
        /// Test the property 'Idref'
        /// </summary>
        [Test]
        public void IdrefTest()
        {
            // TODO unit test for the property 'Idref'
        }
        /// <summary>
        /// Test the property 'Artworks'
        /// </summary>
        [Test]
        public void ArtworksTest()
        {
            // TODO unit test for the property 'Artworks'
        }

    }

}
