/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing Bleedline
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BleedlineTests
    {
        // TODO uncomment below to declare an instance variable for Bleedline
        //private Bleedline instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Bleedline
            //instance = new Bleedline();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Bleedline
        /// </summary>
        [Test]
        public void BleedlineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Bleedline
            //Assert.IsInstanceOfType<Bleedline> (instance, "variable 'instance' is a Bleedline");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Test]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Shape'
        /// </summary>
        [Test]
        public void ShapeTest()
        {
            // TODO unit test for the property 'Shape'
        }
        /// <summary>
        /// Test the property 'Thickness'
        /// </summary>
        [Test]
        public void ThicknessTest()
        {
            // TODO unit test for the property 'Thickness'
        }
        /// <summary>
        /// Test the property 'Rect'
        /// </summary>
        [Test]
        public void RectTest()
        {
            // TODO unit test for the property 'Rect'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'BleedSource'
        /// </summary>
        [Test]
        public void BleedSourceTest()
        {
            // TODO unit test for the property 'BleedSource'
        }
        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [Test]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }
        /// <summary>
        /// Test the property 'Margins'
        /// </summary>
        [Test]
        public void MarginsTest()
        {
            // TODO unit test for the property 'Margins'
        }
        /// <summary>
        /// Test the property 'ShapeModified'
        /// </summary>
        [Test]
        public void ShapeModifiedTest()
        {
            // TODO unit test for the property 'ShapeModified'
        }
        /// <summary>
        /// Test the property 'MarginsAdjusted'
        /// </summary>
        [Test]
        public void MarginsAdjustedTest()
        {
            // TODO unit test for the property 'MarginsAdjusted'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
