/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing Connector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConnectorTests
    {
        // TODO uncomment below to declare an instance variable for Connector
        //private Connector instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Connector
            //instance = new Connector();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Connector
        /// </summary>
        [Test]
        public void ConnectorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Connector
            //Assert.IsInstanceOfType<Connector> (instance, "variable 'instance' is a Connector");
        }


        /// <summary>
        /// Test the property 'Thing'
        /// </summary>
        [Test]
        public void ThingTest()
        {
            // TODO unit test for the property 'Thing'
        }

    }

}
