/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing DctMediaRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DctMediaRulesTests
    {
        // TODO uncomment below to declare an instance variable for DctMediaRules
        //private DctMediaRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DctMediaRules
            //instance = new DctMediaRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DctMediaRules
        /// </summary>
        [Test]
        public void DctMediaRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DctMediaRules
            //Assert.IsInstanceOfType<DctMediaRules> (instance, "variable 'instance' is a DctMediaRules");
        }


        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Test]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
