/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing DctToolStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DctToolStatsTests
    {
        // TODO uncomment below to declare an instance variable for DctToolStats
        //private DctToolStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DctToolStats
            //instance = new DctToolStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DctToolStats
        /// </summary>
        [Test]
        public void DctToolStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DctToolStats
            //Assert.IsInstanceOfType<DctToolStats> (instance, "variable 'instance' is a DctToolStats");
        }


        /// <summary>
        /// Test the property 'Tool'
        /// </summary>
        [Test]
        public void ToolTest()
        {
            // TODO unit test for the property 'Tool'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'DownLength'
        /// </summary>
        [Test]
        public void DownLengthTest()
        {
            // TODO unit test for the property 'DownLength'
        }
        /// <summary>
        /// Test the property 'UpLength'
        /// </summary>
        [Test]
        public void UpLengthTest()
        {
            // TODO unit test for the property 'UpLength'
        }
        /// <summary>
        /// Test the property 'Beam'
        /// </summary>
        [Test]
        public void BeamTest()
        {
            // TODO unit test for the property 'Beam'
        }

    }

}
