/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing Device
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceTests
    {
        // TODO uncomment below to declare an instance variable for Device
        //private Device instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Device
            //instance = new Device();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Device
        /// </summary>
        [Test]
        public void DeviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Device
            //Assert.IsInstanceOfType<Device> (instance, "variable 'instance' is a Device");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Test]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'AllowPassThrough'
        /// </summary>
        [Test]
        public void AllowPassThroughTest()
        {
            // TODO unit test for the property 'AllowPassThrough'
        }
        /// <summary>
        /// Test the property 'Connections'
        /// </summary>
        [Test]
        public void ConnectionsTest()
        {
            // TODO unit test for the property 'Connections'
        }
        /// <summary>
        /// Test the property 'Costing'
        /// </summary>
        [Test]
        public void CostingTest()
        {
            // TODO unit test for the property 'Costing'
        }
        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Test]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
        /// <summary>
        /// Test the property 'Script'
        /// </summary>
        [Test]
        public void ScriptTest()
        {
            // TODO unit test for the property 'Script'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'MediaRules'
        /// </summary>
        [Test]
        public void MediaRulesTest()
        {
            // TODO unit test for the property 'MediaRules'
        }
        /// <summary>
        /// Test the property 'Placement'
        /// </summary>
        [Test]
        public void PlacementTest()
        {
            // TODO unit test for the property 'Placement'
        }
        /// <summary>
        /// Test the property 'ProcessType'
        /// </summary>
        [Test]
        public void ProcessTypeTest()
        {
            // TODO unit test for the property 'ProcessType'
        }
        /// <summary>
        /// Test the property 'FeedType'
        /// </summary>
        [Test]
        public void FeedTypeTest()
        {
            // TODO unit test for the property 'FeedType'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
