/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing DmCosting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DmCostingTests
    {
        // TODO uncomment below to declare an instance variable for DmCosting
        //private DmCosting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DmCosting
            //instance = new DmCosting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DmCosting
        /// </summary>
        [Test]
        public void DmCostingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DmCosting
            //Assert.IsInstanceOfType<DmCosting> (instance, "variable 'instance' is a DmCosting");
        }


        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'CostPerArea'
        /// </summary>
        [Test]
        public void CostPerAreaTest()
        {
            // TODO unit test for the property 'CostPerArea'
        }
        /// <summary>
        /// Test the property 'CostPerAreaUnits'
        /// </summary>
        [Test]
        public void CostPerAreaUnitsTest()
        {
            // TODO unit test for the property 'CostPerAreaUnits'
        }
        /// <summary>
        /// Test the property 'CostPer1up'
        /// </summary>
        [Test]
        public void CostPer1upTest()
        {
            // TODO unit test for the property 'CostPer1up'
        }
        /// <summary>
        /// Test the property 'SteelRules'
        /// </summary>
        [Test]
        public void SteelRulesTest()
        {
            // TODO unit test for the property 'SteelRules'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
