/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing ExportPdfReportResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExportPdfReportResourceTests
    {
        // TODO uncomment below to declare an instance variable for ExportPdfReportResource
        //private ExportPdfReportResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExportPdfReportResource
            //instance = new ExportPdfReportResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExportPdfReportResource
        /// </summary>
        [Test]
        public void ExportPdfReportResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExportPdfReportResource
            //Assert.IsInstanceOfType<ExportPdfReportResource> (instance, "variable 'instance' is a ExportPdfReportResource");
        }


        /// <summary>
        /// Test the property 'Idref'
        /// </summary>
        [Test]
        public void IdrefTest()
        {
            // TODO unit test for the property 'Idref'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Preset'
        /// </summary>
        [Test]
        public void PresetTest()
        {
            // TODO unit test for the property 'Preset'
        }

    }

}
