/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing Grade
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GradeTests
    {
        // TODO uncomment below to declare an instance variable for Grade
        //private Grade instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Grade
            //instance = new Grade();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Grade
        /// </summary>
        [Test]
        public void GradeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Grade
            //Assert.IsInstanceOfType<Grade> (instance, "variable 'instance' is a Grade");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Test]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'GradeDisplay'
        /// </summary>
        [Test]
        public void GradeDisplayTest()
        {
            // TODO unit test for the property 'GradeDisplay'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'WeightUnits'
        /// </summary>
        [Test]
        public void WeightUnitsTest()
        {
            // TODO unit test for the property 'WeightUnits'
        }
        /// <summary>
        /// Test the property 'WeightType'
        /// </summary>
        [Test]
        public void WeightTypeTest()
        {
            // TODO unit test for the property 'WeightType'
        }
        /// <summary>
        /// Test the property 'Caliper'
        /// </summary>
        [Test]
        public void CaliperTest()
        {
            // TODO unit test for the property 'Caliper'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'CostUnits'
        /// </summary>
        [Test]
        public void CostUnitsTest()
        {
            // TODO unit test for the property 'CostUnits'
        }
        /// <summary>
        /// Test the property 'AnySheetSize'
        /// </summary>
        [Test]
        public void AnySheetSizeTest()
        {
            // TODO unit test for the property 'AnySheetSize'
        }
        /// <summary>
        /// Test the property 'Sheets'
        /// </summary>
        [Test]
        public void SheetsTest()
        {
            // TODO unit test for the property 'Sheets'
        }
        /// <summary>
        /// Test the property 'Rolls'
        /// </summary>
        [Test]
        public void RollsTest()
        {
            // TODO unit test for the property 'Rolls'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
