/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing LayoutPlacedEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LayoutPlacedEntityTests
    {
        // TODO uncomment below to declare an instance variable for LayoutPlacedEntity
        //private LayoutPlacedEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LayoutPlacedEntity
            //instance = new LayoutPlacedEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LayoutPlacedEntity
        /// </summary>
        [Test]
        public void LayoutPlacedEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LayoutPlacedEntity
            //Assert.IsInstanceOfType<LayoutPlacedEntity> (instance, "variable 'instance' is a LayoutPlacedEntity");
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Placed'
        /// </summary>
        [Test]
        public void PlacedTest()
        {
            // TODO unit test for the property 'Placed'
        }

    }

}
