/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing MotionSpecs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MotionSpecsTests
    {
        // TODO uncomment below to declare an instance variable for MotionSpecs
        //private MotionSpecs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MotionSpecs
            //instance = new MotionSpecs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MotionSpecs
        /// </summary>
        [Test]
        public void MotionSpecsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MotionSpecs
            //Assert.IsInstanceOfType<MotionSpecs> (instance, "variable 'instance' is a MotionSpecs");
        }


        /// <summary>
        /// Test the property 'Velocity'
        /// </summary>
        [Test]
        public void VelocityTest()
        {
            // TODO unit test for the property 'Velocity'
        }
        /// <summary>
        /// Test the property 'Acceleration'
        /// </summary>
        [Test]
        public void AccelerationTest()
        {
            // TODO unit test for the property 'Acceleration'
        }

    }

}
