/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing OverlapTileEdge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OverlapTileEdgeTests
    {
        // TODO uncomment below to declare an instance variable for OverlapTileEdge
        //private OverlapTileEdge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OverlapTileEdge
            //instance = new OverlapTileEdge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OverlapTileEdge
        /// </summary>
        [Test]
        public void OverlapTileEdgeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OverlapTileEdge
            //Assert.IsInstanceOfType<OverlapTileEdge> (instance, "variable 'instance' is a OverlapTileEdge");
        }


        /// <summary>
        /// Test the property 'Overlap'
        /// </summary>
        [Test]
        public void OverlapTest()
        {
            // TODO unit test for the property 'Overlap'
        }
        /// <summary>
        /// Test the property 'NoImage'
        /// </summary>
        [Test]
        public void NoImageTest()
        {
            // TODO unit test for the property 'NoImage'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
