/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing PlanStatusEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlanStatusEntityTests
    {
        // TODO uncomment below to declare an instance variable for PlanStatusEntity
        //private PlanStatusEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlanStatusEntity
            //instance = new PlanStatusEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlanStatusEntity
        /// </summary>
        [Test]
        public void PlanStatusEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlanStatusEntity
            //Assert.IsInstanceOfType<PlanStatusEntity> (instance, "variable 'instance' is a PlanStatusEntity");
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'RunningTime'
        /// </summary>
        [Test]
        public void RunningTimeTest()
        {
            // TODO unit test for the property 'RunningTime'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'LowestCost'
        /// </summary>
        [Test]
        public void LowestCostTest()
        {
            // TODO unit test for the property 'LowestCost'
        }
        /// <summary>
        /// Test the property 'LowestWaste'
        /// </summary>
        [Test]
        public void LowestWasteTest()
        {
            // TODO unit test for the property 'LowestWaste'
        }
        /// <summary>
        /// Test the property 'LowestLayouts'
        /// </summary>
        [Test]
        public void LowestLayoutsTest()
        {
            // TODO unit test for the property 'LowestLayouts'
        }

    }

}
