/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing PressUnits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PressUnitsTests
    {
        // TODO uncomment below to declare an instance variable for PressUnits
        //private PressUnits instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PressUnits
            //instance = new PressUnits();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PressUnits
        /// </summary>
        [Test]
        public void PressUnitsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PressUnits
            //Assert.IsInstanceOfType<PressUnits> (instance, "variable 'instance' is a PressUnits");
        }


        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Coatings'
        /// </summary>
        [Test]
        public void CoatingsTest()
        {
            // TODO unit test for the property 'Coatings'
        }
        /// <summary>
        /// Test the property 'Foils'
        /// </summary>
        [Test]
        public void FoilsTest()
        {
            // TODO unit test for the property 'Foils'
        }

    }

}
