/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing PressEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PressEntityTests
    {
        // TODO uncomment below to declare an instance variable for PressEntity
        //private PressEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PressEntity
            //instance = new PressEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PressEntity
        /// </summary>
        [Test]
        public void PressEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PressEntity
            //Assert.IsInstanceOfType<PressEntity> (instance, "variable 'instance' is a PressEntity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Test]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }
        /// <summary>
        /// Test the property 'SpeedUnits'
        /// </summary>
        [Test]
        public void SpeedUnitsTest()
        {
            // TODO unit test for the property 'SpeedUnits'
        }
        /// <summary>
        /// Test the property 'CostPerHour'
        /// </summary>
        [Test]
        public void CostPerHourTest()
        {
            // TODO unit test for the property 'CostPerHour'
        }
        /// <summary>
        /// Test the property 'MakeReadyTime'
        /// </summary>
        [Test]
        public void MakeReadyTimeTest()
        {
            // TODO unit test for the property 'MakeReadyTime'
        }
        /// <summary>
        /// Test the property 'NumberOfColors'
        /// </summary>
        [Test]
        public void NumberOfColorsTest()
        {
            // TODO unit test for the property 'NumberOfColors'
        }
        /// <summary>
        /// Test the property 'MinRunLength'
        /// </summary>
        [Test]
        public void MinRunLengthTest()
        {
            // TODO unit test for the property 'MinRunLength'
        }
        /// <summary>
        /// Test the property 'BackSinglePass'
        /// </summary>
        [Test]
        public void BackSinglePassTest()
        {
            // TODO unit test for the property 'BackSinglePass'
        }
        /// <summary>
        /// Test the property 'Workstyle'
        /// </summary>
        [Test]
        public void WorkstyleTest()
        {
            // TODO unit test for the property 'Workstyle'
        }
        /// <summary>
        /// Test the property 'BackNumberOfColors'
        /// </summary>
        [Test]
        public void BackNumberOfColorsTest()
        {
            // TODO unit test for the property 'BackNumberOfColors'
        }
        /// <summary>
        /// Test the property 'BackSpeedReduction'
        /// </summary>
        [Test]
        public void BackSpeedReductionTest()
        {
            // TODO unit test for the property 'BackSpeedReduction'
        }
        /// <summary>
        /// Test the property 'MultiPass'
        /// </summary>
        [Test]
        public void MultiPassTest()
        {
            // TODO unit test for the property 'MultiPass'
        }
        /// <summary>
        /// Test the property 'MinSheetWidth'
        /// </summary>
        [Test]
        public void MinSheetWidthTest()
        {
            // TODO unit test for the property 'MinSheetWidth'
        }
        /// <summary>
        /// Test the property 'MaxSheetWidth'
        /// </summary>
        [Test]
        public void MaxSheetWidthTest()
        {
            // TODO unit test for the property 'MaxSheetWidth'
        }
        /// <summary>
        /// Test the property 'MinSheetHeight'
        /// </summary>
        [Test]
        public void MinSheetHeightTest()
        {
            // TODO unit test for the property 'MinSheetHeight'
        }
        /// <summary>
        /// Test the property 'MaxSheetHeight'
        /// </summary>
        [Test]
        public void MaxSheetHeightTest()
        {
            // TODO unit test for the property 'MaxSheetHeight'
        }
        /// <summary>
        /// Test the property 'MinStockThickness'
        /// </summary>
        [Test]
        public void MinStockThicknessTest()
        {
            // TODO unit test for the property 'MinStockThickness'
        }
        /// <summary>
        /// Test the property 'MaxStockThickness'
        /// </summary>
        [Test]
        public void MaxStockThicknessTest()
        {
            // TODO unit test for the property 'MaxStockThickness'
        }
        /// <summary>
        /// Test the property 'MinStockWeight'
        /// </summary>
        [Test]
        public void MinStockWeightTest()
        {
            // TODO unit test for the property 'MinStockWeight'
        }
        /// <summary>
        /// Test the property 'MaxStockWeight'
        /// </summary>
        [Test]
        public void MaxStockWeightTest()
        {
            // TODO unit test for the property 'MaxStockWeight'
        }
        /// <summary>
        /// Test the property 'WeightUnits'
        /// </summary>
        [Test]
        public void WeightUnitsTest()
        {
            // TODO unit test for the property 'WeightUnits'
        }
        /// <summary>
        /// Test the property 'WeightType'
        /// </summary>
        [Test]
        public void WeightTypeTest()
        {
            // TODO unit test for the property 'WeightType'
        }
        /// <summary>
        /// Test the property 'SheetHandling'
        /// </summary>
        [Test]
        public void SheetHandlingTest()
        {
            // TODO unit test for the property 'SheetHandling'
        }
        /// <summary>
        /// Test the property 'ImageMargins'
        /// </summary>
        [Test]
        public void ImageMarginsTest()
        {
            // TODO unit test for the property 'ImageMargins'
        }
        /// <summary>
        /// Test the property 'ContentMargins'
        /// </summary>
        [Test]
        public void ContentMarginsTest()
        {
            // TODO unit test for the property 'ContentMargins'
        }
        /// <summary>
        /// Test the property 'Gripper'
        /// </summary>
        [Test]
        public void GripperTest()
        {
            // TODO unit test for the property 'Gripper'
        }
        /// <summary>
        /// Test the property 'DefaultPlate'
        /// </summary>
        [Test]
        public void DefaultPlateTest()
        {
            // TODO unit test for the property 'DefaultPlate'
        }

    }

}
