/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing RfwfpResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RfwfpResultTests
    {
        // TODO uncomment below to declare an instance variable for RfwfpResult
        //private RfwfpResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RfwfpResult
            //instance = new RfwfpResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RfwfpResult
        /// </summary>
        [Test]
        public void RfwfpResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RfwfpResult
            //Assert.IsInstanceOfType<RfwfpResult> (instance, "variable 'instance' is a RfwfpResult");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Processes'
        /// </summary>
        [Test]
        public void ProcessesTest()
        {
            // TODO unit test for the property 'Processes'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'ExternalMessages'
        /// </summary>
        [Test]
        public void ExternalMessagesTest()
        {
            // TODO unit test for the property 'ExternalMessages'
        }
        /// <summary>
        /// Test the property 'ProcessType'
        /// </summary>
        [Test]
        public void ProcessTypeTest()
        {
            // TODO unit test for the property 'ProcessType'
        }
        /// <summary>
        /// Test the property 'SetupTime'
        /// </summary>
        [Test]
        public void SetupTimeTest()
        {
            // TODO unit test for the property 'SetupTime'
        }
        /// <summary>
        /// Test the property 'TotalLayouts'
        /// </summary>
        [Test]
        public void TotalLayoutsTest()
        {
            // TODO unit test for the property 'TotalLayouts'
        }
        /// <summary>
        /// Test the property 'SetupLayouts'
        /// </summary>
        [Test]
        public void SetupLayoutsTest()
        {
            // TODO unit test for the property 'SetupLayouts'
        }
        /// <summary>
        /// Test the property 'WasteLayouts'
        /// </summary>
        [Test]
        public void WasteLayoutsTest()
        {
            // TODO unit test for the property 'WasteLayouts'
        }
        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Test]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'InkCost'
        /// </summary>
        [Test]
        public void InkCostTest()
        {
            // TODO unit test for the property 'InkCost'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
