/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing RollEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RollEntityTests
    {
        // TODO uncomment below to declare an instance variable for RollEntity
        //private RollEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RollEntity
            //instance = new RollEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RollEntity
        /// </summary>
        [Test]
        public void RollEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RollEntity
            //Assert.IsInstanceOfType<RollEntity> (instance, "variable 'instance' is a RollEntity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'StockId'
        /// </summary>
        [Test]
        public void StockIdTest()
        {
            // TODO unit test for the property 'StockId'
        }
        /// <summary>
        /// Test the property 'GradeId'
        /// </summary>
        [Test]
        public void GradeIdTest()
        {
            // TODO unit test for the property 'GradeId'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'CostUnits'
        /// </summary>
        [Test]
        public void CostUnitsTest()
        {
            // TODO unit test for the property 'CostUnits'
        }
        /// <summary>
        /// Test the property 'Grain'
        /// </summary>
        [Test]
        public void GrainTest()
        {
            // TODO unit test for the property 'Grain'
        }

    }

}
