/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing Rotation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RotationTests
    {
        // TODO uncomment below to declare an instance variable for Rotation
        //private Rotation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rotation
            //instance = new Rotation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rotation
        /// </summary>
        [Test]
        public void RotationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Rotation
            //Assert.IsInstanceOfType<Rotation> (instance, "variable 'instance' is a Rotation");
        }


        /// <summary>
        /// Test the property 'RotationType'
        /// </summary>
        [Test]
        public void RotationTypeTest()
        {
            // TODO unit test for the property 'RotationType'
        }
        /// <summary>
        /// Test the property 'CustomValues'
        /// </summary>
        [Test]
        public void CustomValuesTest()
        {
            // TODO unit test for the property 'CustomValues'
        }

    }

}
