/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing RuleItemEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleItemEntityTests
    {
        // TODO uncomment below to declare an instance variable for RuleItemEntity
        //private RuleItemEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleItemEntity
            //instance = new RuleItemEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleItemEntity
        /// </summary>
        [Test]
        public void RuleItemEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuleItemEntity
            //Assert.IsInstanceOfType<RuleItemEntity> (instance, "variable 'instance' is a RuleItemEntity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ValueType'
        /// </summary>
        [Test]
        public void ValueTypeTest()
        {
            // TODO unit test for the property 'ValueType'
        }
        /// <summary>
        /// Test the property '_Operator'
        /// </summary>
        [Test]
        public void _OperatorTest()
        {
            // TODO unit test for the property '_Operator'
        }
        /// <summary>
        /// Test the property 'ValueNumber'
        /// </summary>
        [Test]
        public void ValueNumberTest()
        {
            // TODO unit test for the property 'ValueNumber'
        }
        /// <summary>
        /// Test the property 'ValueScalar'
        /// </summary>
        [Test]
        public void ValueScalarTest()
        {
            // TODO unit test for the property 'ValueScalar'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
