/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing SaveJobResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaveJobResourceTests
    {
        // TODO uncomment below to declare an instance variable for SaveJobResource
        //private SaveJobResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaveJobResource
            //instance = new SaveJobResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaveJobResource
        /// </summary>
        [Test]
        public void SaveJobResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaveJobResource
            //Assert.IsInstanceOfType<SaveJobResource> (instance, "variable 'instance' is a SaveJobResource");
        }


        /// <summary>
        /// Test the property 'Idref'
        /// </summary>
        [Test]
        public void IdrefTest()
        {
            // TODO unit test for the property 'Idref'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'EmbedArtwork'
        /// </summary>
        [Test]
        public void EmbedArtworkTest()
        {
            // TODO unit test for the property 'EmbedArtwork'
        }

    }

}
