/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing ThumbnailEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ThumbnailEntityTests
    {
        // TODO uncomment below to declare an instance variable for ThumbnailEntity
        //private ThumbnailEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ThumbnailEntity
            //instance = new ThumbnailEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThumbnailEntity
        /// </summary>
        [Test]
        public void ThumbnailEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThumbnailEntity
            //Assert.IsInstanceOfType<ThumbnailEntity> (instance, "variable 'instance' is a ThumbnailEntity");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Test]
        public void MediaTypeTest()
        {
            // TODO unit test for the property 'MediaType'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

    }

}
