/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing TimeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimeInfoTests
    {
        // TODO uncomment below to declare an instance variable for TimeInfo
        //private TimeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimeInfo
            //instance = new TimeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeInfo
        /// </summary>
        [Test]
        public void TimeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimeInfo
            //Assert.IsInstanceOfType<TimeInfo> (instance, "variable 'instance' is a TimeInfo");
        }


        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Test]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }
        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Test]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }

    }

}
