/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TiliaLabs.Phoenix.Api;
using TiliaLabs.Phoenix.Model;
using TiliaLabs.Phoenix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TiliaLabs.Phoenix.Test
{
    /// <summary>
    ///  Class for testing WfopCosting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WfopCostingTests
    {
        // TODO uncomment below to declare an instance variable for WfopCosting
        //private WfopCosting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WfopCosting
            //instance = new WfopCosting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WfopCosting
        /// </summary>
        [Test]
        public void WfopCostingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WfopCosting
            //Assert.IsInstanceOfType<WfopCosting> (instance, "variable 'instance' is a WfopCosting");
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Test]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'Setup'
        /// </summary>
        [Test]
        public void SetupTest()
        {
            // TODO unit test for the property 'Setup'
        }
        /// <summary>
        /// Test the property 'RunningWaste'
        /// </summary>
        [Test]
        public void RunningWasteTest()
        {
            // TODO unit test for the property 'RunningWaste'
        }
        /// <summary>
        /// Test the property 'MinimumCostPerLayout'
        /// </summary>
        [Test]
        public void MinimumCostPerLayoutTest()
        {
            // TODO unit test for the property 'MinimumCostPerLayout'
        }
        /// <summary>
        /// Test the property 'SetupPerColor'
        /// </summary>
        [Test]
        public void SetupPerColorTest()
        {
            // TODO unit test for the property 'SetupPerColor'
        }
        /// <summary>
        /// Test the property 'RunLengthRange'
        /// </summary>
        [Test]
        public void RunLengthRangeTest()
        {
            // TODO unit test for the property 'RunLengthRange'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
