/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TiliaLabs.Phoenix.Client.SwaggerDateConverter;

namespace TiliaLabs.Phoenix.Model
{
    /// <summary>
    /// Specific devices
    /// </summary>
    [DataContract]
        public partial class AssetRefDevice :  IEquatable<AssetRefDevice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetRefDevice" /> class.
        /// </summary>
        /// <param name="frozenAsset">frozenAsset.</param>
        public AssetRefDevice(Device frozenAsset = default(Device))
        {
            this.FrozenAsset = frozenAsset;
        }
        
        /// <summary>
        /// Gets or Sets FrozenAsset
        /// </summary>
        [DataMember(Name="frozenAsset", EmitDefaultValue=false)]
        public Device FrozenAsset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssetRefDevice {\n");
            sb.Append("  FrozenAsset: ").Append(FrozenAsset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetRefDevice);
        }

        /// <summary>
        /// Returns true if AssetRefDevice instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetRefDevice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetRefDevice input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FrozenAsset == input.FrozenAsset ||
                    (this.FrozenAsset != null &&
                    this.FrozenAsset.Equals(input.FrozenAsset))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FrozenAsset != null)
                    hashCode = hashCode * 59 + this.FrozenAsset.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
