/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TiliaLabs.Phoenix.Client.SwaggerDateConverter;

namespace TiliaLabs.Phoenix.Model
{
    /// <summary>
    /// Standard rule-based tiling
    /// </summary>
    [DataContract]
        public partial class StandardTiling : Tiling, IEquatable<StandardTiling>, IValidatableObject
    {
        /// <summary>
        /// Starting corner for tile placement order
        /// </summary>
        /// <value>Starting corner for tile placement order</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StartEnum
        {
            /// <summary>
            /// Enum TopLeft for value: Top Left
            /// </summary>
            [EnumMember(Value = "Top Left")]
            TopLeft = 1,
            /// <summary>
            /// Enum TopRight for value: Top Right
            /// </summary>
            [EnumMember(Value = "Top Right")]
            TopRight = 2,
            /// <summary>
            /// Enum BottomLeft for value: Bottom Left
            /// </summary>
            [EnumMember(Value = "Bottom Left")]
            BottomLeft = 3,
            /// <summary>
            /// Enum BottomRight for value: Bottom Right
            /// </summary>
            [EnumMember(Value = "Bottom Right")]
            BottomRight = 4        }
        /// <summary>
        /// Starting corner for tile placement order
        /// </summary>
        /// <value>Starting corner for tile placement order</value>
        [DataMember(Name="start", EmitDefaultValue=false)]
        public StartEnum? Start { get; set; }
        /// <summary>
        /// Order rule to use from start corner to define tile placement order
        /// </summary>
        /// <value>Order rule to use from start corner to define tile placement order</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum OrderEnum
        {
            /// <summary>
            /// Enum SnakingVertical for value: Snaking Vertical
            /// </summary>
            [EnumMember(Value = "Snaking Vertical")]
            SnakingVertical = 1,
            /// <summary>
            /// Enum SnakingHorizontal for value: Snaking Horizontal
            /// </summary>
            [EnumMember(Value = "Snaking Horizontal")]
            SnakingHorizontal = 2,
            /// <summary>
            /// Enum ZigzagVertical for value: Zigzag Vertical
            /// </summary>
            [EnumMember(Value = "Zigzag Vertical")]
            ZigzagVertical = 3,
            /// <summary>
            /// Enum ZigzagHorizontal for value: Zigzag Horizontal
            /// </summary>
            [EnumMember(Value = "Zigzag Horizontal")]
            ZigzagHorizontal = 4        }
        /// <summary>
        /// Order rule to use from start corner to define tile placement order
        /// </summary>
        /// <value>Order rule to use from start corner to define tile placement order</value>
        [DataMember(Name="order", EmitDefaultValue=false)]
        public OrderEnum? Order { get; set; }
        /// <summary>
        /// Tiling entity type.  &#x27;StandardTiling&#x27; for standard tiling and &#x27;CustomTiling&#x27; for custom tiling types
        /// </summary>
        /// <value>Tiling entity type.  &#x27;StandardTiling&#x27; for standard tiling and &#x27;CustomTiling&#x27; for custom tiling types</value>
        public override TypeEnum Type { get; } = TypeEnum.StandardTiling;
        /// <summary>
        /// Initializes a new instance of the <see cref="StandardTiling" /> class.
        /// </summary>
        /// <param name="name">Name (required).</param>
        /// <param name="description">Description.</param>
        /// <param name="notes">Notes.</param>
        /// <param name="start">Starting corner for tile placement order.</param>
        /// <param name="order">Order rule to use from start corner to define tile placement order.</param>
        /// <param name="horizontalRule">horizontalRule.</param>
        /// <param name="horizontalMethod">horizontalMethod.</param>
        /// <param name="verticalRule">verticalRule.</param>
        /// <param name="verticalMethod">verticalMethod.</param>
        /// <param name="properties">Custom properties.</param>
        /// <param name="path">Path.</param>
        public StandardTiling(string name = default(string), string description = default(string), string notes = default(string), StartEnum? start = default(StartEnum?), OrderEnum? order = default(OrderEnum?), TilingRule horizontalRule = default(TilingRule), TilingMethod horizontalMethod = default(TilingMethod), TilingRule verticalRule = default(TilingRule), TilingMethod verticalMethod = default(TilingMethod), List<PropertyObject> properties = default(List<PropertyObject>), string path = default(string))
            :  base(name, description, notes, properties, path)
        {
            this.Start = start;
            this.Order = order;
            this.HorizontalRule = horizontalRule;
            this.HorizontalMethod = horizontalMethod;
            this.VerticalRule = verticalRule;
            this.VerticalMethod = verticalMethod;
        }
        
        /// <summary>
        /// Gets or Sets HorizontalRule
        /// </summary>
        [DataMember(Name="horizontal-rule", EmitDefaultValue=false)]
        public TilingRule HorizontalRule { get; set; }

        /// <summary>
        /// Gets or Sets HorizontalMethod
        /// </summary>
        [DataMember(Name="horizontal-method", EmitDefaultValue=false)]
        public TilingMethod HorizontalMethod { get; set; }

        /// <summary>
        /// Gets or Sets VerticalRule
        /// </summary>
        [DataMember(Name="vertical-rule", EmitDefaultValue=false)]
        public TilingRule VerticalRule { get; set; }

        /// <summary>
        /// Gets or Sets VerticalMethod
        /// </summary>
        [DataMember(Name="vertical-method", EmitDefaultValue=false)]
        public TilingMethod VerticalMethod { get; set; }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StandardTiling {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  HorizontalRule: ").Append(HorizontalRule).Append("\n");
            sb.Append("  HorizontalMethod: ").Append(HorizontalMethod).Append("\n");
            sb.Append("  VerticalRule: ").Append(VerticalRule).Append("\n");
            sb.Append("  VerticalMethod: ").Append(VerticalMethod).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StandardTiling);
        }

        /// <summary>
        /// Returns true if StandardTiling instances are equal
        /// </summary>
        /// <param name="input">Instance of StandardTiling to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StandardTiling input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.Start == input.Start ||
                    (this.Start != null &&
                    this.Start.Equals(input.Start))
                ) &&
                (
                    this.Order == input.Order ||
                    (this.Order != null &&
                    this.Order.Equals(input.Order))
                ) &&
                (
                    this.HorizontalRule == input.HorizontalRule ||
                    (this.HorizontalRule != null &&
                    this.HorizontalRule.Equals(input.HorizontalRule))
                ) &&
                (
                    this.HorizontalMethod == input.HorizontalMethod ||
                    (this.HorizontalMethod != null &&
                    this.HorizontalMethod.Equals(input.HorizontalMethod))
                ) &&
                (
                    this.VerticalRule == input.VerticalRule ||
                    (this.VerticalRule != null &&
                    this.VerticalRule.Equals(input.VerticalRule))
                ) &&
                (
                    this.VerticalMethod == input.VerticalMethod ||
                    (this.VerticalMethod != null &&
                    this.VerticalMethod.Equals(input.VerticalMethod))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Start != null)
                    hashCode = hashCode * 59 + this.Start.GetHashCode();
                if (this.Order != null)
                    hashCode = hashCode * 59 + this.Order.GetHashCode();
                if (this.HorizontalRule != null)
                    hashCode = hashCode * 59 + this.HorizontalRule.GetHashCode();
                if (this.HorizontalMethod != null)
                    hashCode = hashCode * 59 + this.HorizontalMethod.GetHashCode();
                if (this.VerticalRule != null)
                    hashCode = hashCode * 59 + this.VerticalRule.GetHashCode();
                if (this.VerticalMethod != null)
                    hashCode = hashCode * 59 + this.VerticalMethod.GetHashCode();
                if (this.Properties != null)
                    hashCode = hashCode * 59 + this.Properties.GetHashCode();
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
