/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TiliaLabs.Phoenix.Client.SwaggerDateConverter;

namespace TiliaLabs.Phoenix.Model
{
    /// <summary>
    /// Stepped Speed Entry
    /// </summary>
    [DataContract]
        public partial class SteppedSpeedEntry :  IEquatable<SteppedSpeedEntry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SteppedSpeedEntry" /> class.
        /// </summary>
        /// <param name="range">Range (required).</param>
        /// <param name="speed">Speed (required).</param>
        public SteppedSpeedEntry(double? range = default(double?), double? speed = default(double?))
        {
            // to ensure "range" is required (not null)
            if (range == null)
            {
                throw new InvalidDataException("range is a required property for SteppedSpeedEntry and cannot be null");
            }
            else
            {
                this.Range = range;
            }
            // to ensure "speed" is required (not null)
            if (speed == null)
            {
                throw new InvalidDataException("speed is a required property for SteppedSpeedEntry and cannot be null");
            }
            else
            {
                this.Speed = speed;
            }
        }
        
        /// <summary>
        /// Range
        /// </summary>
        /// <value>Range</value>
        [DataMember(Name="range", EmitDefaultValue=false)]
        public double? Range { get; set; }

        /// <summary>
        /// Speed
        /// </summary>
        /// <value>Speed</value>
        [DataMember(Name="speed", EmitDefaultValue=false)]
        public double? Speed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SteppedSpeedEntry {\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SteppedSpeedEntry);
        }

        /// <summary>
        /// Returns true if SteppedSpeedEntry instances are equal
        /// </summary>
        /// <param name="input">Instance of SteppedSpeedEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SteppedSpeedEntry input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Range == input.Range ||
                    (this.Range != null &&
                    this.Range.Equals(input.Range))
                ) && 
                (
                    this.Speed == input.Speed ||
                    (this.Speed != null &&
                    this.Speed.Equals(input.Speed))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Range != null)
                    hashCode = hashCode * 59 + this.Range.GetHashCode();
                if (this.Speed != null)
                    hashCode = hashCode * 59 + this.Speed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
