/* 
 * tilia Phoenix API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TiliaLabs.Phoenix.Client.SwaggerDateConverter;

namespace TiliaLabs.Phoenix.Model
{
    /// <summary>
    /// Variable sizes tiling rule
    /// </summary>
    [DataContract]
        public partial class VariableSizesRule : TilingRule, IEquatable<VariableSizesRule>, IValidatableObject
    {
        /// <summary>
        /// Tiling rule type.  &#x27;FixedNumber&#x27; for fixed number rule, &#x27;FixedSize&#x27; for fixed size rule and &#x27;VariableSizes&#x27; for variable sizes rule
        /// </summary>
        /// <value>Tiling rule type.  &#x27;FixedNumber&#x27; for fixed number rule, &#x27;FixedSize&#x27; for fixed size rule and &#x27;VariableSizes&#x27; for variable sizes rule</value>
        public override TypeEnum Type { get; } = TypeEnum.VariableSizes;
        /// <summary>
        /// Initializes a new instance of the <see cref="VariableSizesRule" /> class.
        /// </summary>
        /// <param name="sizes">Custom sizes to use to create tiles in the given dimension (required).</param>
        public VariableSizesRule(List<double?> sizes = default(List<double?>))
        {
            // to ensure "sizes" is required (not null)
            if (sizes == null)
            {
                throw new InvalidDataException("sizes is a required property for VariableSizesRule and cannot be null");
            }
            else
            {
                this.Sizes = sizes;
            }
        }
        
        /// <summary>
        /// Custom sizes to use to create tiles in the given dimension
        /// </summary>
        /// <value>Custom sizes to use to create tiles in the given dimension</value>
        [DataMember(Name="sizes", EmitDefaultValue=false)]
        public List<double?> Sizes { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VariableSizesRule {\n");
            sb.Append("  Sizes: ").Append(Sizes).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VariableSizesRule);
        }

        /// <summary>
        /// Returns true if VariableSizesRule instances are equal
        /// </summary>
        /// <param name="input">Instance of VariableSizesRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VariableSizesRule input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.Sizes == input.Sizes ||
                    this.Sizes != null &&
                    input.Sizes != null &&
                    this.Sizes.SequenceEqual(input.Sizes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Sizes != null)
                    hashCode = hashCode * 59 + this.Sizes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
